apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: s36meft75-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: s36meft75-nodejs 
  name: s36meft75-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: s36meft75-nodejs 
